[build]
  command = "npm install"  # Instala dependencias
  functions = "functions"  # Directorio de funciones

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200